version: "3"

services:

  teiler-dashboard:
#    image: teiler-dashboard
    build: .

#    depends_on:
#      - teiler-backend
    ports:
      - 4200:80
    environment:
      DEFAULT_LANGUAGE: "DE"
      TEILER_BACKEND_URL: "http://localhost:8085"
      OIDC_URL: "http://localhost:8380/login"
      OIDC_REALM: "teiler"
      OIDC_CLIENT_ID: "teiler"
      TEILER_ADMIN_NAME: "Max Mustermann"
      TEILER_ADMIN_EMAIL: "max.mustermann@teiler-example.com"
      TEILER_ADMIN_PHONE: "+49 123 456789"
      TEILER_PROJECT: "DKTK"
      TEILER_DASHBOARD_SERVER_NAME: "localhost"
      TEILER_ORCHESTRATOR_URL: "http://localhost:9000"
      TEILER_DASHBOARD_HTTP_RELATIVE_PATH: ""
      TEILER_ORCHESTRATOR_HTTP_RELATIVE_PATH: ""
      REPORTER_DEFAULT_TEMPLATE_ID: "ccp-qb"
      EXPORTER_DEFAULT_TEMPLATE_ID: "ccp"


#  teiler-backend :
#    image: teiler-backend
