name: Docker CI

on:
  push:
    branches:
      - main
      - develop
    # Build then a new version is tagged
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
      - develop
  schedule:
    # Build every night at 1am
    - cron: '0 1 * * *'
jobs:
  build:
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      image-name: "samply/teiler-dashboard"
      push-to: dockerhub
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

